[project]
name = "tdbc"
version = "v0.1.0"
description = "tdbc / toadback"
authors = [
    {name = "Cees van de Griend", email = "cees.van.de.griend@griend.eu"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "GPL"}
