name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pdm install
          
      - name: Test
        run: |
          pdm test
          
      - name: Lint
        run: |
          pdm lint
          
      - name: Format
        run: |
          pdm format
          
      - name: Build
        run: |
          pdm build
